name: Build Camera App APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Unzip Uploaded File
      run: unzip "googel cmara app.zip" -d source_code

    - name: Build Debug APK
      # --continue फ्लैग सारे कोड एरर्स को एक साथ लॉग में प्रिंट करेगा
      run: |
        PROJECT_ROOT=$(find source_code -name "gradlew" -printf '%h\n' -quit)
        cd "$PROJECT_ROOT"
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace --continue

    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: always() # बिल्ड फेल होने पर भी आर्टिफैक्ट सेव करने की कोशिश करेगा
      with:
        name: Camera-App-Debug-APK
        path: source_code/**/app/build/outputs/apk/debug/*.apk
